### ISSUE TITLE
getAllScreens not working on Linux openSUSE Tumbleweed

### ISSUE THREAD

**Issue by tryptech** [Kalmat/PyWinCtl#11]
I received an error here https://github.com/tryptech/obs-zoom-and-follow/issues/33

It seems as though there is a particular issue with this specific setup. I will get more details but for now, maybe some Linux configs aren't playing nice?

**Comment by Kalmat** [comment]
Hi! It's quite possible that some configs do not properly work. Linux distributions and WMs are a heck of a mess. I managed to test on the mainstream distributions: Ubuntu/Gnome, Ubuntu/Unity, Mint/Cinnamon and Raspbian/LXDE. Since it's totally impossible to install all combinations, I knew this module should be improved by receiving other users issues/comments.

Regarding this case, it's crucial we get the WM this user is using, since OpenSUSE TumbleWeed doesn't have a default WM if I am not wrong.

**Comment by SanctusStreams** [comment]
i am on windows and having the same issue- it says as follows:

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Users/myname/Documents/OBS SCRIPTS/obs-zoom-and-follow-master(1)/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 2, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.30
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'

**Comment by SanctusStreams** [comment]
When using windows command prompt I have an error installing PyWinCtl. It says:

"could not find version that satisfies the requirement numpy~=1.21(from pywinctl) (from versions 1.30* - 1.19.5*)   no matching distribution found for numpy~= 1.21 (from pywinclt)"

*when it says 1.30 and 1.19.5 it also lists every version in between however I do not have the time to type all those out- and I cannot copy my command prompt because I am a newb :p

**Comment by Kalmat** [comment]
Hi! I don't think this is the same issue since the OP was able to install pywinctl, but received an error when running getAllScreens() method. I think your issue is related to numpy module (either you don't have it installed in your system or the version is not compatible).

Anyway, download the updated wheel file from [here](https://github.com/Kalmat/PyWinCtl/tree/master/dist), and run this from command line:

`python3 -m pip install PyWinCtl-0.0.36-py3-none-any.whl --force-reinstall
`

I have removed the numpy dependency, so it should work now.

Please let me know if it works.

**Comment by SanctusStreams** [comment]
In the command prompt it says "python is not installed" and in the command prompt for python 3.6.8 it says "invalid syntax"

._.

**Comment by SanctusStreams** [comment]
Do I need to install this in a particular way? like select the path that python is in first or something? I am sorry I am a 100% newb here i just want my mouse follow and zoom to work xd

**Comment by Kalmat** [comment]
HAHAHAHA! That's totally different.

I'm not an OBS expert, sorry. I found a video explaining how to install Python3 and zoom script within OBS: [here](https://www.youtube.com/watch?v=t7RhpvlVte0).

Otherwise, I suggest you ask the Zoom-and-Follow script author (tryptech) directly by opening an issue [here](https://github.com/tryptech/obs-zoom-and-follow/issues). I know He usually answers all issues.

Let me know if you get to make any progress
