### ISSUE TITLE
Why use Apple Script instead of Quartz?

### ISSUE THREAD

**Issue by abrichr** [Kalmat/PyWinCtl#29]
Hello, and thank you for your work on updating PyGetWindow!

I'm curious about the decision to move to Apple Script instead of Quartz. As you mention in the docs (and is noted in other issues), the performance is quite poor. (For my purposes it's effectively unusable.)

To demonstrate:

```
import pygetwindow as pgw
import pywinctl as pwc
import time

NUM_ITERATIONS = 20
pgw_durations = []
pwc_durations = []

for _ in range(NUM_ITERATIONS):
    pgw_start_time = time.perf_counter()
    pgw_win = pgw.getActiveWindow()
    pgw_duration = time.perf_counter() - pgw_start_time
    pgw_durations.append(pgw_duration)

    pwc_start_time = time.perf_counter()
    pwc_win = pwc.getActiveWindow()
    pwc_duration = time.perf_counter() - pwc_start_time
    pwc_durations.append(pwc_duration)

mean_pgw_duration = sum(pgw_durations) / NUM_ITERATIONS
print(f"{mean_pgw_duration=}")
mean_pwc_duration = sum(pwc_durations) / NUM_ITERATIONS
print(f"{mean_pwc_duration=}")
factor = mean_pwc_duration / mean_pgw_duration
print(f"{factor=}")
```

Output:
```
mean_pgw_duration=0.003413116199999977
mean_pwc_duration=0.5713422643999999
factor=167.39607763720548
```

It appears that the Apple Script implementation is over 100x slower than the Quartz implementation of the same functionality. So why not use Quartz where possible?

Thanks!

**Comment by Kalmat** [comment]
Hi! Thank you for your interest! So sorry to hear it's not suitable in your case.

Yes, Quartz is way faster than AppScript (anything is faster, actually, HAHAHAHA!). The problems when using Quartz are:

1. Quartz uses a number of dictionaries for every window/application. It's not an object you can use to do anything with it afterwards. It's just informative and static (it will not reflect any later change, so you will need to constantly "refresh" it).

```
        {
        kCGWindowAlpha = 1;
        kCGWindowBounds =         {
            Height = 365;
            Width = 585;
            X = 0;
            Y = 23;
        };
        kCGWindowIsOnscreen = 1;
        kCGWindowLayer = 0;
        kCGWindowMemoryUsage = 1152;
        kCGWindowName = "pywinctl \U2014 osascript \U25c2 Python _pywinctl_macos.py \U2014 80\U00d724";
        kCGWindowNumber = 48;
        kCGWindowOwnerName = Terminal;
        kCGWindowOwnerPID = 554;
        kCGWindowSharingState = 1;
        kCGWindowStoreType = 1;
    }
```

2. This dictionary has some "promissing" fields: kCGWindowNumber and kCGWindowName. Nevertheless the kCGWindowNumber doesn't match any other id you can get/use in any other way, so you have no link to the actual window when using other mechanisms (AppKit, AppScript, ...) to manipulate it. On the other hand, kCGWindowName (required by AppScript since Apple also eliminated "id" from AppScript) is optional (and empty for most apps) since Catalina.
Besides, you get this other dict related to "Terminal" when listing all windows using Quartz (CGWindowListCopyWindowInfo):

```
        {
        kCGWindowAlpha = 1;
        kCGWindowBounds =         {
            Height = 22;
            Width = 1920;
            X = 0;
            Y = 0;
        kCGWindowLayer = 24;
        kCGWindowMemoryUsage = 173336;
        kCGWindowNumber = 46;
        kCGWindowOwnerName = Terminal;
        kCGWindowOwnerPID = 554;
        kCGWindowSharingState = 1;
        kCGWindowStoreType = 2;
    },
```

Though there are slight differences between them, I'm not sure wether you can rely on it to distinguish them (I mean, to effectively know which one is really A or THE window... maybe kCGWindowStoreType=2? Will it be like this in all cases?).

See what happens when I get the windows again, with Terminal maximized (fullscreen):

```
  {
        kCGWindowAlpha = 1;
        kCGWindowBounds =         {
            Height = 1080;
            Width = 1920;
            X = 0;
            Y = 0;
        };
        kCGWindowIsOnscreen = 1;
        kCGWindowLayer = 0;
        kCGWindowMemoryUsage = 1152;
        kCGWindowName = "pywinctl \U2014 osascript \U25c2 Python _pywinctl_macos.py \U2014 270\U00d776";
        kCGWindowNumber = 48;
        kCGWindowOwnerName = Terminal;
        kCGWindowOwnerPID = 554;
        kCGWindowSharingState = 1;
        kCGWindowStoreType = 1;
    },
```      
kCGWindowNumber has changed, but also kCGWindowName!!!

3. In short, I think Apple deliberatedly suppressed all possible ways to combine Quartz and AppScript (in fact, my first version was a "mix" of both, but I had to completely re-write it when I tested it in Catalina+). 

Sorry for the long explanation. I will think of it again with this perspective to try to find some ways to optimize it, but I have little expectations, to be honest. If you have any idea or you think you can help in any way, you are more than welcome!!!

Besides, my AppScript skills are very limited (I basically took ideas googling around). Perhaps one day a "compassive" real expert can help!

Thanks again!

**Comment by Kalmat** [comment]
Hi again!

After testing and googling (and remembering... HAHAHA!) a little bit, I can't figure out how to solve the issue in a general, valid in all cases, way. Take a look to this:

https://developer.apple.com/documentation/coregraphics/kcgwindowname?language=objc

especially to: "Note that few applications set the Quartz window name". Definitely, Apple does not like anybody messing around other apps windows!!!

I will keep on trying. In the mean time, and in your case, you can use this workaround, checking if any of those values change every N miliseconds. Please, try this and let me know you thoughts:

```
import time

import AppKit
import Quartz

WS = AppKit.NSWorkspace.sharedWorkspace()


def macOS_getActiveWindow():
    app = WS.frontmostApplication()
    windows = Quartz.CGWindowListCopyWindowInfo(Quartz.kCGWindowListExcludeDesktopElements | Quartz.kCGWindowListOptionOnScreenOnly, Quartz.kCGNullWindowID)
    for win in windows:
        if win.get(Quartz.kCGWindowLayer, "") == 0:
            return [app.localizedName(), app.processIdentifier(), win.get("kCGWindowName", ""), win.get("kCGWindowNumber", None), win.get("kCGWindowBounds", None)]
    return None


start = time.time()
win = macOS_getActiveWindow()
print(time.time() - start)
print(win)

while True:
    try:
        newWin = macOS_getActiveWindow()
        if win != newWin:
            win = newWin
            print("CHANGED!!!")
        time.sleep(0.1)
    except KeyboardInterrupt:
        break
```

Bear in mind you can do this check on a separate Thread or using a non-blocking Timer (not time.sleep(), I mean). Let me know if you need help on this as well.

Regards!
