### ISSUE TITLE
get wrong titles in Debian X11

### ISSUE THREAD

**Issue by lazebird** [Kalmat/PyWinCtl#87]
>>> pwc.getAllTitles()
['T', '1', 'Q', 'a', '微', 'p', 'K', '●']

>>> pwc.getAllAppsWindowsTitles()
{'ToDesk': ['T'], 'SecureCRT': ['1'], 'qq': ['Q'], 'nautilus': ['a'], 'wechat': ['微'], 'eog': ['p'], 'msedge': ['U'], 'code': ['●']}

![image](https://github.com/Kalmat/PyWinCtl/assets/12560868/a52effa3-3e43-49dc-854f-3e7920851b58)

**Comment by Kalmat** [comment]
Hi! Thank you for your feedback!

Very strange case, because I had identified this problem in Cinnamon, not in GNOME. Anyway, this will be fixed in next version (I am trying to finish all tests but I'm stuck trying to borrow an actual macOS, sorry). If you need a solution in the meantime, I can provide you with a pre-release wheel you can work with (tested in Windows 10 and 11, as well as Ubuntu/GNOME, Mint/Cinnamon and Manjaro/KDE)

**Comment by lazebird** [comment]
no problem, i will wait for your next release, thanks

**Comment by lazebird** [comment]
test success after upgrade to 0.4

**Comment by Kalmat** [comment]
Great news! Thanx.
