### ISSUE TITLE
SyntaxError: annotated name '_updateScreens' can't be global

### ISSUE THREAD

**Issue by ccc469** [Kalmat/PyWinCtl#89]
![image](https://github.com/Kalmat/PyWinCtl/assets/27529250/0bcac0ec-3fd6-4474-9af4-377fe0049b5a)

# test.py
import pywinctl

print(pywinctl.getActiveWindow())

OS:  Windows 10 (Windows Feature Experience Pack 120.2212.551.0)

I installed windows 10 on my virtual machine. Is it because of this problem?

**Comment by Kalmat** [comment]
Hi! Sorry for my late reply. These days are really busy.

PyWinCtl doesn't support Python 3.7 anymore because of some limitations related to annotations and typing. Futhermore, Python 3.7 reached its End Of Life (EOF) on 2019. If you update your python version to a more recent one (e.g. 3.10 or 3.11), it should work fine!!!

Please let me know if this solves your issue.

Thank you!

**Comment by ccc469** [comment]
Yes it works fine when I use a higher version of python
